### ISSUE TITLE
Error in Vignette xmR - "recalc" actually defaults to TRUE

### ISSUE THREAD

**Issue by bbrewington** [Zanidean/xmrr#2]
**recalc is automatically set to TRUE in the xmr function definition:**
https://github.com/Zanidean/xmrr/blob/d4c8cfc804c118b5f7c5353dce65f107447c2b1b/R/xmR.R#L23

**3 mentions of "recalc" in the vignette**
https://github.com/Zanidean/xmrr/blob/d4c8cfc804c118b5f7c5353dce65f107447c2b1b/vignettes/xmR.Rmd#L29
https://github.com/Zanidean/xmrr/blob/d4c8cfc804c118b5f7c5353dce65f107447c2b1b/vignettes/xmR.Rmd#L62
https://github.com/Zanidean/xmrr/blob/d4c8cfc804c118b5f7c5353dce65f107447c2b1b/vignettes/xmR.Rmd#L78-L82

**Comment by Zanidean** [comment]
Thanks for the heads up. 

I'll fix this in the next release.
